name: krishjagirdar
favicon: null
layout_spectrum: 0.39056973485276103
typography_spectrum: 0.9133912220131606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232323'
    - '#ebeced'
    - '#878788'
    - '#cbcbcb'
    - '#666666'
  brandStrength: 0.5
  lightness: 0.6324171437881887
  saturation: 0.27411169931292534
  rhythmicContrast: 0.9680237576831132
purpose: []
