name: krishjagirdar
favicon: null
layout_spectrum: 0.2186
typography_spectrum: 0.9133912220131606
title: Thoughts from a Driven Mind.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232323'
    - '#ebeced'
    - '#878788'
    - '#cbcbcb'
    - '#666666'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
