name: krishjagirdar
favicon: null
layout_spectrum: 0.39056973485276103
typography_spectrum: 0.9133912220131606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5047096104826778
  lightness: 0.6324171437881887
  saturation: 0.27411169931292534
  rhythmicContrast: 0.9680237576831132
purpose: []
